language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: a9496d3199f3e17a15a3554bc252c2fa
  app:
  run: rails db:migrate

#test for pr
